# Generated by Django 2.0.6 on 2018-06-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='portal',
        ),
        migrations.RemoveField(
            model_name='article',
            name='url',
        ),
    ]
